### ISSUE TITLE
Rewrite resource bundling rules

### ISSUE THREAD

**Issue by allevato** [bazelbuild/rules_apple#11]
`objc_bundle` and `objc_bundle_library` should be deprecated and replaced with a single unified rule written in Skylark.

The rule would not do any bundling itself, but merely propagate `AppleResource` providers that tell the depending target where (i.e., what `*.bundle` directory) the resources should be included in.

`objc_bundle` makes very specific assumptions about the file layout (that is, it copies it verbatim, preserving any directory structure), so we need to figure out how to support that cleanly. `structured_resources` gets us part of the way there, but there are subtle path-handling cases that differ.

**Comment by jerrymarino** [comment]
@allevato I'm wondering about the case where we have a `.bundle` which has the same name as a bazel target.

Let's say we need a bundle called `Stripe.bundle` and an bazel target called `Stripe`, which is a static library.

It looks like in the current rules, the bundle takes on the name of the target. I don't think it is currently possible to do this in bazel `objc_library("Stripe")` and `objc_bundle_library("Stripe")`.

Would this be solved with the rewrite?

**Comment by allevato** [comment]
I anticipate adding something like an optional `bundle_name` attribute on all the bundling rules (so not just resource bundles, but application/extension/framework/etc bundles as well) that would let users override the bundle's name if they don't want to use the name of the target (which would be the default).

So, you'd be able to write:

```python
the_new_resource_bundle_rule(
    name = "StripeResourceBundle",
    bundle_name = "Stripe",  # .bundle would be automatically added
    ...
)

objc_library(
    name = "Stripe",
    bundles = [":StripeResourceBundle"],
    ...
)
```

In fact, I've spun this into #70 since it's not specific to the resource bundle rules.

**Comment by jerrymarino** [comment]
@allevato  Awesome, I think `bundle_name` would solve my issue here! I'm looking forward to using #70 👍 

Do you have any suggestions of how to handle this until #70 is ready?

I thought of a few potential ideas:
- wrap `objc_bundle_library` in a macro, and write a gen_rule to rename the bundle.
- have a script that runs before the final application is bundled, and rename everything.

**Comment by allevato** [comment]
#75 was just pushed that fixes #70 for application/extensions/frameworks, but not yet for `objc_bundle_library` (because it's not using the same bundling logic yet). That'll take a little bit longer.

The genrule-renaming approach isn't likely to work because `objc_bundle_library` propagates its resources to the bundling rules using the `ObjcProvider`, which would be lost if you wedge a genrule in the middle.

Can you rename the `objc_library` target instead? The name of that target doesn't matter, aside from the usability of having it named something different.

**Comment by jerrymarino** [comment]
@allevato wow awesome! Thanks for pushing this fix.

You're right, a new naming convention in the top level targets could work. I think this is a good temporarily solution until #70 is done  and would only require a few tweaks. 

Otherwise, I'd need do it as in p2: ( `ipa_post_processor` ) combined with logic to determine the correct name from the bundle target name ( also reasonably easy ).

I'll keep my eye on #70 🥇

**Comment by jerrymarino** [comment]
@allevato I thought of another easier way: we can already import bundles that are pre "built" with `objc_bundle`.

So, instead of using `objc_bundle_library`, I can build the bundle by simply making a directory called `Stripe.bundle` and glob all of the inputs I was originally using to `objc_bundle_library`. I think I can pull this off with a basic `genrule` in bazel ( and if not, just use some command line rule ).

I can easily migrate off this to the new bundle rules once they're done 💯

**Comment by sergiocampama** [comment]
I believe `apple_bundle_import` and `apple_resource_bundle` should provide the required functionality.
