### ISSUE TITLE
`objc_library` target with Cocoa import fails build

### ISSUE THREAD

**Issue by math4tots** [bazelbuild/rules_apple#116]
Hi, I hope this is the right place to ask this. bazel-discuss seemed too broad, but I couldn't find a bazel-rules-apple discuss, and I wasn't sure where to turn `^_^;`

My current test workspace looks like this:

* foo
  * main.mm
  * BUILD
* WORKSPACE

WORKSPACE looks like:

```
git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    tag = "0.0.1",
)
```

`foo/BUILD` looks like:

```
objc_library(
    name = "lib",
    srcs = ["main.mm"],
    sdk_frameworks = ["Cocoa"],
)

apple_binary(
    name = "foo",
    deps = [":lib"],
    platform_type = "macos",
)
```

and `foo/main.mm` looks like:

```
#import <Cocoa/Cocoa.h>
#import <iostream>
using namespace std;

int main() {
  cout << "Hello world!" << endl;
}
```

It seems like I can build and run the binary just fine:

```
kkmbp:tutorial math4tots$ bazel run //foo:foo_lipobin
..........................................................
INFO: Found 1 target...
Target //foo:foo_lipobin up-to-date:
  bazel-out/ios_x86_64-fastbuild/bin/foo/foo_lipobin
INFO: Elapsed time: 11.894s, Critical Path: 1.15s

INFO: Running command line: bazel-out/ios_x86_64-fastbuild/bin/foo/foo_lipobin
Hello world!
```

However, when I try to build the `objc_library` rule by itself it fails:

```
kkmbp:tutorial math4tots$ bazel build //foo:lib
INFO: Found 1 target...
ERROR: /Users/math4tots/tmp/bz/examples/tutorial/foo/BUILD:1:1: C++ compilation of rule '//foo:lib' failed (Exit 1).
foo/main.mm:1:9: fatal error: 'Cocoa/Cocoa.h' file not found
#import <Cocoa/Cocoa.h>
        ^~~~~~~~~~~~~~~
1 error generated.
Target //foo:lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.646s, Critical Path: 0.52s
```

It's funny because if I just change `Cocoa/Cocoa.h` to `UIKit/UIKit.h` it builds just fine.

This is functionally ok, since the final product still builds, but this means I can no longer run `bazel test //...`, since this `objc_library` target is always going to fail.

Am I doing something wrong here? I suppose I could look up and add Cocoa header include path manually as a copt or something, but that seems rather hacky. What's the right way for me to get this to work?

**Comment by sergiocampama** [comment]
This is because for legacy reasons, the default platform that gets set when building an `objc_library` as the top level target is iOS. This is why using UIKit works, but not Cocoa (or any macOS framework)

When you build the `apple_binary`, which has `platform_type = "macos"`, all the dependencies of the `apple_binary` target will have the macOS configuration applied, that's why it builds correctly.

Interestingly enough, if you look at the output path of the `foo` binary, it's `bazel-out/ios_x86_64-fastbuild/bin/foo/foo_lipobin`. Notice the `ios` in the path? This is because the `apple_binary` target is being built with a default top-level configuration of iOS. The `apple_binary` rule will then create a configuration transition for its dependencies that configures them to be built for macOS. (you can `ls blaze-out` to look at the other output folders, which represent the configuration under which those outputs were built).

In general we discourage building `objc_library` targets directly specifically because of this problem, and encourage building targets that imply an `apple_binary` that have the `platform_type` attribute set (e.g. `macos_commandline_application`, which would be great for your use case)

If you *really* want to build an `objc_library` target from the command line, you can use the [`--apple_platform_type=macos`](https://github.com/bazelbuild/bazel/blob/80a34dc97799961201e6dce20fd58dd08022c032/src/main/java/com/google/devtools/build/lib/rules/apple/AppleCommandLineOptions.java#L224) command line flag which will set the top level platform to be macOS, but I'm not sure if that feature has rolled out in mainstream bazel, it is relatively new.

Hope this clarifies a bit the state of things.
