### ISSUE TITLE
ios_dynamic_framework - wrong .swiftmodule and .swiftdoc

### ISSUE THREAD

**Issue by ivoleko** [bazelbuild/rules_apple#1624]
**ios_dynamic_framework** rule allows deps to have another deps, and I can clearly see that more deps I add, binary become bigger and bigger, which is expected behavior for static libs. 

However, `.swiftmodule` and `.swiftdoc` files inside final framework are not generated correctly. Take a look at this example:
```

ios_dynamic_framework(
    name = "TheFramework",
    bundle_name = "TheFramework",
    ...
    deps = [
        "TheFrameworkLib",
    ]
)
swift_library(
    name = "TheFrameworkLib",
    module_name: "TheFramework"
    srcs = [
        # publicly available  
    ],
    deps = [
        ":InternalLib"
    ],
)
swift_library(
    name = "InternalLib",
    srcs = [
        # internal files  
    ],
)
```

It builds successfully, and I can see by the size of the framework that InternalLib is also included in the binary. However, when I import this `TheFramework.framework` in the new iOS project (without Bazel), I am getting error:` Missing required module "InternalLib"`. 

The reason for this is that generated` .swiftmodule` file is the same file generated for `TheFrameworkLib.a`, so it is missing everything related` InternalLib`. You can check it clearly in the `swift_dynamic_framework_aspect.bzl` that it takes just single .swiftmodule from all swiftdeps for further processing.

**Comment by keith** [comment]
Frameworks can only bundle a single swiftmodule file, this is a limitation in swift itself. If you want to have transitive swift dependencies from your top level framework module you must import them with `@_implementationOnly` so that they are not exposed to downstream users of the framework. If you need to expose public api from the transitive modules you need to vendor multiple frameworks.

**Comment by ivoleko** [comment]
@keith thank you for your respond. I am fully aware that framework can contain only single swiftmodule. 

However, I made a simple test. I created new Xcode framework project and imported `TheFrameworkLib.a` together with `TheFrameworkLib.swiftmodule` and `InternalLib.swiftmodule`  (I’ve got all files from derives of the Bazel building process).
I successfully compiled and generated new dynamic framework that has newly created **single .swiftmodule** that works like a charm. No more `Missing required module error` because obviously this newly generated .swiftmodule contains everything from both libraries.

Can you please explain me little more about `@_implementationOnly`? 
Are you pointing on `private_deps`? Because I tried to use `private_deps` in above example, but final result is same:
`Missing required module "InternalLib"`

**Comment by keith** [comment]
Can you attach your example project

**Comment by ivoleko** [comment]
@keith I guess you are asking for Xcode project I described above, where I imported `TheFrameworkLib.a `together with `TheFrameworkLib.swiftmodule` and `InternalLib.swiftmodule` and I was able to get new .swiftmodule.

You can download it here: 
https://www.dropbox.com/s/7hqqtbiywlt81xz/Archive.zip

It is same structure as described at the first message, just different names of the libs. Instead of the name `InternalLib`, here the name is `Emoji`. 
.swiftmodule and .swiftdoc files are added trough `Swift compiler - Search paths` inside project's build settings.

**Comment by ivoleko** [comment]
@keith or you asking about example project from first message?

It is super simple. Just single class **A** inside `TheFrameworkLib` and single class **B** inside `InternalLib`. I do not even need to call anything from `InternalLib`. It is enough just to `import InternalLib` inside class **A**.

**Comment by keith** [comment]
The difference in your Xcode sample project is that by default Xcode embeds paths into the generated swiftmodule file that point to the underlying modules that your public module relies on. If you flip `SWIFT_SERIALIZE_DEBUGGING_OPTIONS=NO` in the xcodeproj, and try to use your framework externally, it will fail (it should also fail if you actually moved it to a different computer in this case). Bazel's paths are not portable for this, so you don't get the same behavior (and ideally you flip on `--features=swift.cacheable_swiftmodules` which disables the same setting as the one mentioned above).

I think for your case since you don't need to expose any public API you can mark your imports like:

```
@_implementationOnly import LykaTelegram
```

and add the module to `private_deps` instead of `deps`, and it should work as you expect.

**Comment by ivoleko** [comment]
Thanks @keith for clarification. I was not aware of `@_implementationOnly` in Swift.
