### ISSUE TITLE
ApplicationIdentifierPrefix validation error

### ISSUE THREAD

**Issue by jerrymarino** [bazelbuild/rules_apple#169]
Good morning. I've been running into some issues with more of the new plist validation logic. My iOS app and extension has been assumed to work fine for the last several years and the entitlements it's signed with are working as expected. Now when I update to `rules_apple` `4.0.0` I get this error:

> [2018-04-12T20:02:43Z] In target "//Some/iOS/Extension:entitlements"; the entitlements "com.apple.developer.team-identifier" ("SOME") did not match the provisioning profile's "ApplicationIdentifierPrefix" ("['OTHER']").

I dug through all of Apple's documentation, but I couldn't find much info about the `ApplicationIdentifierPrefix`. This was the most relevant doc I could find: https://developer.apple.com/library/content/qa/qa1879/_index.html

For now, [I've just disabled this validation](https://github.com/jerrymarino/rules_apple/commit/115d1fad114a8791c2d0c33243a25b825e9bac9b), since the entitlements on my end didn't change. Without documentation, it is hard to know the right path forward.

Can anyone confirm if this is indeed a requirement? If it's not, I can submit a PR to remove the check so this works for Pinterest.

**Comment by thomasvl** [comment]
Yea, Apple's docs on this are pretty incomplete to say the least.  The check is testing the passed entitlements vs. the default entitlements within the provisioning profile.

It also doesn't help that the simulator and devices have version different feelings about how much things have to match.  The simulator will use some of entitlements, but not validate them against what is in the provisioning profile.  So things that _work_ in the simulator can fail on the device.

Because of the differences between simulator and device, as well as Apple's lack of docs, the rules already have support to control this validation: https://github.com/bazelbuild/rules_apple/blob/master/doc/types.md#entitlements_validation_mode.  As mentioned in the docs, the default is `loose`, so you don't need to edit the sources to change things, just change the `entitlements_validation_mode` on your targets that doesn't seem to follow what all of Apple's examples do.

Can we also get a little more info on your situation?  Can you take a device build, and extract the entitlements and provisioning profile from your app and extension to see if codesign isn't checking the values and instead replacing them as part of the signing process?  Given what we've seen and that qa page notes they all match, it would be interesting if they really didn't in the end, of if codesign was just papering over the error.  If they don't match, it likely is worth talking to Apple to confirm this is really working ok, or could break in the figure.  Having multiple team ids at play in an app seems odd.

**Comment by sergiocampama** [comment]
@jerrymarino any updates?

**Comment by rahul-malik** [comment]
@sergiocampana - We ended up using the entitlements_validation_mode to solve this issue for us. We had to relax the validation IIRC

@jerrymarino - Want to add any specifics from our setup here?

**Comment by jerrymarino** [comment]
Hey all, thanks so much for adding the `entitlements_validation_mode` codepath, that fixes this for us 👍 https://github.com/bazelbuild/rules_apple/commit/5fea3ef85765b5cd99263157e2f366f795bb0c17
