### ISSUE TITLE
Add headermap include documentation

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#1757]
Currently when migrating to bazel you often hit some issues around include paths that affect include performance. One solution to this is headermaps, but that potentially comes with the downside of a headermap per target, which adds many actions to the build. It seems that the best long term solution to this is to add `-I $(SRCROOT)` as your only include path, but this requires you to change all your includes because this isn't common in the iOS community. The community would benefit from documentation around this, and potentially a headermap rule to ease the migration. One question about a specific headermap rule is what forms of imports do you need to expose

**Comment by luispadron** [comment]
A few threads in the Bazel slack have brought this issue up and there is a lot of confusion around it. 

The biggest issue is as you mentioned, which is especially tough to fix when using third party libraries:

> It seems that the best long term solution to this is to add -I $(SRCROOT) as your only include path, but this requires you to change all your includes because this isn't common in the iOS community. 

Xcode generates headermaps by default and so iOS projects end up relying on it. [I recently ran into this](https://bazelbuild.slack.com/archives/CD3QY5C2X/p1703964397357109) as I was looking to test moving our Bazel module off of `rules_ios`. 

Should we consider bringing in a similar rule to what `rules_ios` has here: https://github.com/bazel-ios/rules_ios/tree/master/rules/hmap

I mostly want to to get the conversation/design started since it looks like folks just end up copying that when migrating their iOS projects and having this supported in rules_apple would be nice.
