### ISSUE TITLE
Support choosing between multiple AppIcons

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#231]
Currently because of this check:

https://github.com/bazelbuild/rules_apple/blob/0e593c759eed4b556e6c2d86cf457aa711317bb1/apple/bundling/resource_actions.bzl#L362-L366

If you have multiple app icons in a single xcassets directory like this:

```
AppIcon-Alpha.appiconset
AppIcon-Beta.appiconset
AppIcon-Dev.appiconset
AppIcon.appiconset
```

The build fails. It seems like (at least for iOS, I'm not familiar with how tvOS app icons work) the only reason for this is because otherwise we wouldn't know which name to pass here:

https://github.com/bazelbuild/rules_apple/blob/0e593c759eed4b556e6c2d86cf457aa711317bb1/apple/bundling/resource_actions.bzl#L369

I'm wondering if there's opposition to supporting this feature, or if it's a matter of figuring out the API necessary to support this.

I think in the meantime I could likely create extra xcassets directories for each icon, and switch between those, instead of including all 4 in the same one.

**Comment by keith** [comment]
Previous conversation about this: https://github.com/bazelbuild/rules_apple/issues/123#issuecomment-348984734

**Comment by keith** [comment]
For our use case, commenting out that check and doing a direct glob of the icon we want to use works as expected:

```python
app_icons = native.glob(["Resources/Images/*.xcassets/AppIcon.appiconset"]),
```

In theory we would use a `select` with this to switch between them based on other configuration settings

**Comment by thomasvl** [comment]
Why would you want to ship the other icons?  They are just wasting space and some products use custom icons for non prod that they likely don't ever want to accidentally ship to the AppStore.

Having said that, with iOS's support for custom app icons the user can pick from, there likely will be something in the future to support that, but I think for safety sake, we're still likely to error if we get more than one app icon, because it is a common sign that someone made too big of a glob.

**Comment by allevato** [comment]
@thomasvl is right; include only what you need, using `select` to decide which folder to include based on the app release you're building.

Note that if you ever build without sandboxing, even the `glob` you wrote above isn't sufficient, because `actool` only takes the `.xcassets` folder as an argument and pulls in _everything_ underneath it, regardless of what you write in your glob. (So the filtering you get is a side effect of sandboxing because only the files you asked for are visible.)

A safer approach is to put assets for different release types in different asset catalogs. What you want, instead of the layout you showed above, is this:

```
Assets-Alpha.xcassets/AppIcon.appiconset
Assets-Beta.xcassets/AppIcon.appiconset
Assets-Dev.xcassets/AppIcon.appiconset
Assets.xcassets/AppIcon.appiconset
```

Alternatively, name the final one `Assets-Release.xcassets` and then also have an `Assets.xcassets` for your assets that are not release-type-specific.

```
Assets-Alpha.xcassets/AppIcon.appiconset
Assets-Beta.xcassets/AppIcon.appiconset
Assets-Dev.xcassets/AppIcon.appiconset
Assets-Release.xcassets/AppIcon.appiconset
Assets.xcassets/everything else...
```

The name of the .xcassets folder doesn't matter because they're all merged into a single Assets.car file and the OS doesn't care where they originated from, so you can have as many as you want and divide them up as you wish.

**Comment by keith** [comment]
> Why would you want to ship the other icons? They are just wasting space and some products use custom icons for non prod that they likely don't ever want to accidentally ship to the AppStore.

It appears that actool is smart enough to eliminate other icons starting with `AppIcon`, in our case with this local patch, if you use a tool [like this one](https://github.com/insidegui/AssetCatalogTinkerer) you can see only 1 icon ends up in the final .app bundle.

**Comment by keith** [comment]
I'll have to see how the multiple asset catalog approach works with Xcode since I still want to maintain support with it during our bazel transition.

**Comment by allevato** [comment]
> It appears that actool is smart enough to eliminate other icons starting with AppIcon, in our case with this local patch, if you use a tool like this one you can see only 1 icon ends up in the final .app bundle.

`actool` isn't doing that; the Bazel sandbox is, because it only makes the files you globbed visible. Hence my comment above about it not being 100% safe because it relies on external factors.

> It appears that actool is smart enough to eliminate other icons starting with AppIcon, in our case with this local patch, if you use a tool like this one you can see only 1 icon ends up in the final .app bundle.

Xcode lets you have as many .xcassets folders as you want in a project; just make sure they're members of the correct targets and it'll pass them all to `actool` the same way we do.

**Comment by keith** [comment]
> actool isn't doing that; the Bazel sandbox is, because it only makes the files you globbed visible. Hence my comment above about it not being 100% safe because it relies on external factors.

I'll have to investigate this more but what I said applies to our Xcode builds as well, we only end up with a single icon in the final Assets.car, example: (otherwise there would be a few more colors)

![image](https://user-images.githubusercontent.com/283886/46161849-85e47100-c23b-11e8-9f37-4ba727eaf437.png)

**Comment by keith** [comment]
I've verified this is the case in a sample project as well. Xcode must be using the same logic used to filter this list to exclude the other icons

![image](https://user-images.githubusercontent.com/283886/46162049-0e631180-c23c-11e8-91f5-9c2a11e8087f.png)

**Comment by allevato** [comment]
What's the full command line that Xcode passes to `actool` in that case, out of curiosity?

**Comment by keith** [comment]
Nothing that obviously handles this:

```
CompileAssetCatalog /tmp/app/build.noindex/app/Build/Products/Debug-iphonesimulator/app.app /tmp/app/app/Assets.xcassets (in target: app)
    cd /tmp/app
    /Applications/Xcode-10.0.app/Contents/Developer/usr/bin/actool --output-format human-readable-text --notices --warnings --export-dependency-info /tmp/app/build.noindex/app/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app.build/assetcatalog_dependencies --output-partial-info-plist /tmp/app/build.noindex/app/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app.build/assetcatalog_generated_info.plist --app-icon AppIcon --compress-pngs --enable-on-demand-resources YES --filter-for-device-model iPhone10,4 --filter-for-device-os-version 12.0 --sticker-pack-identifier-prefix com.smileykeith.app.sticker-pack. --target-device iphone --target-device ipad --minimum-deployment-target 12.0 --platform iphonesimulator --product-type com.apple.product-type.application --compile /tmp/app/build.noindex/app/Build/Products/Debug-iphonesimulator/app.app /tmp/app/app/Assets.xcassets
```

**Comment by keith** [comment]
FWIW we worked around this by doing a custom glob based on a `select` statement to grab whichever icon we wanted

**Comment by segiddins** [comment]
> Nothing that obviously handles this:

I believe the `--app-icon AppIcon` is what's handling this in the example Keith posted
