### ISSUE TITLE
Using ios_framework with swift_library 

### ISSUE THREAD

**Issue by keith** [bazelbuild/rules_apple#326]
I started down the path of attempting to integrate an `ios_framework` backed by a `swift_library`, it looks like in this case other `swift_library` targets cannot depend on the produced framework. Is this something that should be supported?

I also noticed that the docs still recommend adding those targets to the `frameworks` attribute of `ios_application` targets, could this be done through deps instead?

**Comment by thomasvl** [comment]
At the moment, `ios_framework` is really just for bundling, i.e. - two apps can have different sets of extensions/etc. so they should each decide how they want their dependencies split into frameworks, rather that some shared code deciding it is always a framework.  If the shared code decides, you can end up with all shared code deciding that, and suddenly you force apps to have dozens (or hundreds) of frameworks, which isn't good for iOS launch times.

So, the `swift_library` never _depends_ on an `ios_framework`, instead its `deps` always still point to other `*_library` rules.  The `ios_framework` usages just provide sorta a parallel structure to say how the code gets bundled between all the binary target.

@sergiocampama has a doc he's working on to better explain all this, other things just keep taking higher priority over getting it done.  🙁

**Comment by keith** [comment]
Thanks for the context. For our use case really what we want is the ability to use dynamic frameworks for local builds to decrease link time when iterating. So I'm interested in eventually working on something that could facilitate this

**Comment by thomasvl** [comment]
That can actually be really easy, set everything up, including the `ios_framework` rules.  Then, use a `--define` (or something) that you check in a `select()` to provide the value for the `ios_application` `frameworks` attribute.  i.e. - provide an empty list, no frameworks, provide a list, you get framework instead.

**Comment by keith** [comment]
Interesting, so it "just works" even though the `ios_application` otherwise only has a single dep, and all the "real" deps are in the `swift_library` rule that contains the app delegate?

**Comment by thomasvl** [comment]
That `swift_library` will still have `deps` on all the rest of the code.  So while itself might be tiny, everything else is still coming through `deps`.

**Comment by keith** [comment]
Awesome! We'll give that a shot, thanks for the info

**Comment by sergiocampama** [comment]
@keith did that work for you? We also made [this guide](https://github.com/bazelbuild/rules_apple/blob/master/doc/frameworks.md) available to explain the use cases for `ios_framework`.

Making them available through `deps` is very tricky since it may lead to runtime duplicate symbol warnings, since you may get the same base dependencies multiple times through dylibs that don't know about each other, so it wouldn't be feasible to ensure proper deduplication.

**Comment by keith** [comment]
We haven't tried it but I will close it and re-open when we do if we find issues

**Comment by ghvg1313** [comment]
@sergiocampama we are trying to achieve the same goal here to allow local developer use dynamic linking pipeline, what we did is essentially emitting a ios_framework on top of every apple library (swift or objc)
Initial problem is that each dylib produced by `ios_framework` will load **every** transitive dependency libraries, this essentially cause the top app binary's loading commands exceed mach-o limit (and of course unnecessary loading, which is less of an issue comparing to load overflow). I think @keith got the same result here.

We tried to only link against direct deps, then realized it's pretty hard to determine what libraries to link against, for example, we have:
target A:
```
public protocol Foo {}
```

target B:
```
public protocol Bar: Foo {}
```

target C: 
```
public class BarImp: Bar {}
```

In the case above, linking C dynamically requires both A and B present

not sure if there's a better way to determine the libraries to load other than turning on auto linking.

**Comment by wweevv-johndpope** [comment]
"Making them available through deps is very tricky since it may lead to runtime duplicate symbol warnings, since you may get the same base dependencies multiple times through dylibs that don't know about each other, so it wouldn't be feasible to ensure proper deduplication."

@sergiocampama  - I'm attempting to use firebase with bazel - and running into this problem.
Not sure how to fix it - 
https://github.com/firebase/firebase-ios-sdk/issues/6115

my BUILD files
https://gist.github.com/wweevv-johndpope/fad4feb6f108c3df56033f28799d1d4c/



problem I have is - this line - seems to be bundling up firebase into this telegramui swift_library - and therefore making it all appear twice.
https://gist.github.com/wweevv-johndpope/1bfb9a41ab4029db1ef6df1d9687b40d#file-test-swift-L56
