### ISSUE TITLE
Support Swift implemented frameworks in apple_static_framework_import

### ISSUE THREAD

**Issue by kastiglione** [bazelbuild/rules_apple#557]
Can we make `apple_static_framework_import` support frameworks that are implemented in Swift? Currently, using a framework implemented in Swift will result in linker errors, for missing libraries such as `swiftFoundation`. Perhaps by adding something like a `swift = True` keyword argument?

**Comment by kastiglione** [comment]
cc @rebello95

**Comment by sergiocampama** [comment]
@allevato are we internally depending on the autolink behavior to link against the swift dylibs? @kastiglione how is the static framework being produced? does it contain the autolink markers?

**Comment by kastiglione** [comment]
@sergiocampama Here is the rule: https://github.com/lyft/envoy-mobile/blob/bb6b5d8fca9f6e24f749b7e3637bf0ec80c9eddc/bazel/swift_static_framework.bzl.

Good point, the solution could simply be autolinking.

**Comment by allevato** [comment]
IIRC the problem is that we still tell `apple_binary` precisely which search paths to look for libraries in, and we only add the Swift libs directory if we detect Swift in the dependency graph. This is done through an aspect looking for targets that propagate `SwiftInfo`, so `swift_library` works, but framework targets don't.

(I'm assuming that the binary the framework is eventually being linked into doesn't contain any Swift libraries in its dependency graph itself, right? Otherwise this _should_ be working, since there would be other Swift to force those paths to get added.)

I don't think we need a special flag for this; the presence of a `.swiftmodule` or `.swiftinterface` file in the `Modules` directory of the framework being imported would be enough to tell us that Swift is being used and we need to add it to the search paths. (I suppose one edge case would be if the framework was _implemented_ in Swift but didn't _export_ any Swift interfaces, only Objective-C interfaces. Does anyone even do that?)

At this point, is there any reason we don't just update the linking implementation to unconditionally put the Swift lib directory on the search path? Unless I'm blanking on something, that would resolve that last edge case too.

**Comment by kastiglione** [comment]
I don't have the framework on my machine. From memory, I think it might have the autolink markers because I recall there being diagnostic messages saying it couldn't find `swiftFoundation`, etc. I assumed the missing piece was `-L` flags pointing into Xcode's toolchain, where these libs live.

**Comment by kastiglione** [comment]
> (I'm assuming that the binary the framework is eventually being linked into doesn't contain any Swift libraries in its dependency graph itself, right? Otherwise this should be working, since there would be other Swift to force those paths to get added.)

@allevato correct.

**Comment by kastiglione** [comment]
> I don't think we need a special flag for this; the presence of a .swiftmodule or .swiftinterface file in the Modules directory of the framework being imported would be enough to tell us that Swift is being used and we need to add it to the search paths.

This would cover for our case.

**Comment by kastiglione** [comment]
> At this point, is there any reason we don't just update the linking implementation to unconditionally put the Swift lib directory on the search path? Unless I'm blanking on something, that would resolve that last edge case too.

I can't think of any reason not to do this.

**Comment by sergiocampama** [comment]
Ah, so it wasn't missing symbols, it wasn't finding the dylibs during linking... 

The smallest change that will get you rolling will be to detect in the framework imports if there's a swiftmodule/swiftinterface/modulemap file and construct a SwiftInfo provider from that and propagate it. Do you want to take that on @kastiglione ?

**Comment by kastiglione** [comment]
Yep will do.
