### ISSUE TITLE
Error while building ios_static_framework target with `swift.supports_library_evolution` feature disabled

### ISSUE THREAD

**Issue by thii** [bazelbuild/rules_apple#640]
> (14:36:52) ERROR: /private/var/tmp/_bazel_admin/f505423c3d0ea6184f698774196278be/external/MyLibrary/BUILD.bazel:6:1: in @build_bazel_rules_apple//apple/internal/aspects:swift_static_framework_aspect.bzl%swift_static_framework_aspect aspect on apple_static_library rule @MyLibrary//:MyLibraryFramework.intermediate.apple_static_library:
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_admin/f505423c3d0ea6184f698774196278be/external/MyLibrary/BUILD.bazel", line 6
                @build_bazel_rules_apple//apple/internal/aspects:swift_static_framework_aspect.bzl%swift_static_framework_aspect(...)
        File "/private/var/tmp/_bazel_admin/f505423c3d0ea6184f698774196278be/external/build_bazel_rules_apple/apple/internal/aspects/swift_static_framework_aspect.bzl", line 132, in _swift_static_framework_aspect_impl
                swiftinfo.transitive_swiftinterfaces.to_list()[0]
index out of range (index is 0, but sequence has 0 elements)

**Comment by thii** [comment]
`.bazelrc` with this feature disabled:
```
build --features=-swift.supports_library_evolution
```

**Comment by thomasvl** [comment]
You need an interface file to build reusable static libs, the module interface isn't frozen and can't be mixed between compiler versions, so I believe things are working as intended.

**Comment by thomasvl** [comment]
@allevato correct?

**Comment by allevato** [comment]
Right, we intentionally don't support building Swift into `ios_static_framework`s without library evolution enabled, because the intended and supported use case of that rule is to create _distributable_ static frameworks, and the only way to do so in Swift that is resilient (i.e., module-stable going forward) is to generate .swiftinterface files with library evolution turned on.

This is working as intended.

**Comment by acecilia** [comment]
👋 Any chance to reconsider this?

> the intended and supported use case of that rule is to create distributable static frameworks, and the only way to do so in Swift that is resilient

Agree with this. 

But I believe ultimately the decision of enabling/disabling swift evolution is up to the consumer of the rule, if possible. Specially considering that library evolution is still not super stable.

It has been some time since last message, is there currently any way to build without library evolution?
