### ISSUE TITLE
Bitcode flag not working

### ISSUE THREAD

**Issue by schumy** [bazelbuild/rules_apple#667]
Hi all,

I'm trying to build a library(hand tracking from MediaPipe of Google) and for some reason, even with the flag of Bitcode set to yes, I keep getting this error:
myLibrary.a does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

What can I do to solve it?

Thanks

**Comment by allevato** [comment]
It's not clear from your issue which rule you're using to compile your code, but since rules_apple doesn't contain any rules that do compilation, the problem you're running into probably isn't with any of the rules implemented here. If it's an `objc_library`, then you might have better luck filing an issue at https://github.com/bazelbuild/bazel since that rule is implemented there.

**Comment by schumy** [comment]
@allevato this is basically how I'm compiling it from the command line:
bazel build -c opt --config=ios_arm64 mediapipe/examples/ios/handtrackinggpu:HandTrackingGpuApp

The configuration comes as part of the MediaPipe library. I will post under the bezel project.

Thank you!

**Comment by thomasvl** [comment]
Take a look at https://docs.bazel.build/versions/master/command-line-reference.html#flag--apple_bitcode

**Comment by schumy** [comment]
@thomasvl Thanks for pointing that out Thomas. I did have a look there but that made no difference. The outcome is a .a of only 130kb which misses a lot of dependencies.
If I compile it in Xcode, the outcome is an .a that doesn't support bitcode.. 

Any other tip?

**Comment by allevato** [comment]
Closing in favor of bazelbuild/bazel#10374.
