### ISSUE TITLE
`skip_simulator_signing_allowed` should be `True` for `ios_unit_test`

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/rules_apple#710]
In the [Codesign Bundles for the Simulator](https://github.com/bazelbuild/rules_apple/blob/master/doc/common_info.md#codesign-bundles-for-the-simulator-applecodesign_simulator_bundles) section of Common Info it states:

>One exception is XCTest bundles, those do need to be signed for the simulators to load them. The above --define does not change the behavior around signing of these bundles as a result.

This is incorrect. I changed `skip_simulator_signing_allowed` to `True` for `ios_unit_test` and all of our tests continue to pass, including our App Host test. I didn't have any `ios_ui_test` to check, but I believe that statement might continue to hold true for it.

**Comment by keith** [comment]
Any harm in flipping this bit for everyone?

**Comment by thomasvl** [comment]
It comes down to what the test uses as it if it needs to be signed.  There are some api even in the simulator that need to have things signed because they need to have entitlements.  When I did the initial work, it took a like of individual investigations to figure out when something failed because of the removal of the signature.  The APIs don't all error, they might return `nil`, so by the time the test fails, you can be well removed from the code path that made the call.

So changing the default means you likely put everyone into that case of having to go digging see why something started failing.  If you were starting from zero, then, yes, a different default might be easier as folks would hit the error when the added the tests that need to be signed.

I'll also note that tests tend not to be very granular, so any one test method could need it, making it harder to tell as the tests evolve if the flag state could be revisited.

Anyway, that's the background on why I originally stuck with off by default.

**Comment by keith** [comment]
thanks for the context! I wonder if that means we should have an override in the opposite direction that allows opting into no singing instead of opting out.

**Comment by brentleyjones** [comment]
Yeah, my main ask is the ability to disable code signing for XCTest bundles, whatever the method.

**Comment by keith** [comment]
Here's a possible change that could replace the existing flag and be a bit more flexible around which targets you want to opt into this or not https://github.com/bazelbuild/rules_apple/pull/958
