### ISSUE TITLE
Actions that declare directories but don't create those directories fail to build with remote strategy

### ISSUE THREAD

**Issue by thii** [bazelbuild/rules_apple#861]
Currently, there are some resource actions that declare output directories but don't create those directories. Instead, they rely on Bazel's [unexpected behavior](https://github.com/bazelbuild/bazel/issues/6260#issuecomment-444549249) that creates those directories before executing an action. This makes the actions fail to execute with remote execution if the actions require the directories to exist before the execution.

The [documentation for `declare_directory`](https://docs.bazel.build/versions/master/skylark/lib/actions.html#declare_directory) says that
> You must create an action that generates the directory.

The [RBE API documentation](https://github.com/bazelbuild/remote-apis/blob/006a399149dd2dad4eedff247578e94bd957da9c/build/bazel/remote/execution/v2/remote_execution.proto#L512-L514) says that 
> Directories leading up to the output directories (_but not the output directories themselves_) are created by the worker prior to execution

Related:
- https://github.com/bazelbuild/bazel/issues/6260
- https://github.com/bazelbuild/bazel/issues/6393
- https://github.com/bazelbuild/remote-apis/issues/40

**Comment by sergiocampama** [comment]
how does that work? how are rules expected to create an action to create the directory if the directory is an output of the action? this seems to result in either having to wrap the tools in a bash script in order to create the output before invoking the tool or having to modify the tool to do the expected thing, which in many cases is not possible... there is no reason why rbe should require this from the action and not have the executor create the output directory for you, since the worst case is that you have an empty directory which gets deduplicated in the CAS.

**Comment by thii** [comment]
You've said the solutions :P

I imagine you'd have to change the output from a directory to a file, if that's possible. If the directory has to be an output of the action, it seems odd to me that the tool does not create the directory for you. I guess I'll file a radar :).

Having the executor create the output directory for you seems to be the best option, but it's against the REv2 specification (even though some of the RE implementations do that).

**Comment by thii** [comment]
Reported to BuildGrid: https://gitlab.com/BuildGrid/buildgrid/-/issues/330.

**Comment by edbaunton** [comment]
It's worth noting that in v2.1 of RE the distinction between output files and output directories is (dropped)[https://github.com/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto#L493] and it simply becomes an `output_path`. How do you expect this to behave in that situation?

**Comment by thii** [comment]
Since the output directories would become part of the `output_paths`, I would expect the remote executor to create the output directories for you.

**Comment by edbaunton** [comment]
If the request contains an `output_path` of `/path/to/my/file` should it return a directory or a file? The server cannot know.

**Comment by thii** [comment]
Interesting. This seems like a huge unexpected behavior of Bazel that a lot of rules have been depending on.

**Comment by sergiocampama** [comment]
@edbaunton  What was the argument for removing the distinction between files and directories for the outputs? That seems like it limits some of the introspection that could be done on the responses themselves, and it forces this reported issue into a mode that will just make it more difficult to integrate with tools that can not be modified in order to adopt the RE2 expectations.

**Comment by edbaunton** [comment]
The only discussion I could find is [here](https://github.com/bazelbuild/remote-apis/issues/75).

I guess your rule is creating an empty directory and requiring that to be returned?
